### ISSUE TITLE
Download gif for github readme

### ISSUE THREAD

**Issue by amirallami-code** [amirallami-code/binary-search-algorithm#2]
Hi, I want to add a GIF to my readme that shows how the binary search algorithm works, is anybody know a website where I can find gifs like this and download them?

**Comment by vincyy24** [comment]
1. Look for a short/clip on YouTube
2. Speed it up a little if need to
3. Convert to gif - there are various convertors online

**Comment by amirallami-code** [comment]
> > Hi, I want to add a GIF to my readme that shows how the binary search algorithm works, is anybody know a website where I can find gifs like this and download them?
> 
> 1. Look for a short/clip on YouTube
> 2. Speed it up a little if need to
> 3. Convert to gif - there are various convertors online

thanks
